<template>
	<div>
		<table style="border: 1px">
			<tr>
				<th>Elements</th>
				<th>Forms</th>
				<th>Data</th>
				<th>Navigation</th>
				<th>Overlays</th>
				<th>Layouts</th>
			</tr>
			<tr>
				<td>Accordion, Alert, Avatar, Badge, Button, Dropdown, Icon, Kdb, Link, Prograss, Meter, Chip</td>
				<td>Input, Input Menu, Select, Select Menu, Checkbox, Radio Group, Toggle, Range, Form Group, Form</td>
				<td>Table</td>
				<td>Vertical Navigation, Command Palette, Pagination, Tabs, Breadcrumb, Horizontal Navigation</td>
				<td>Modal, Slideover, Popover, Tooltip, Context Menu, Notification</td>
				<td>Card, Container, Skeleton, Divider, Carousel</td>
			</tr>
		</table>
	</div>
	<ExamplesUiAccordion />
	<ExamplesUiAccordion2 />
	<ExamplesUiAccordion3 />
	<ExamplesUiAccordion4 />
	<ExamplesUiAccordion5 />
	<ExamplesUiAccordion6 />
	<ExamplesUiAccordion7 />
	<ExamplesUiAlert />
	<ExamplesUiAlert2 />
	<ExamplesUiAlert3 />
	<ExamplesUiAlert4 />
	<ExamplesUiAlert5 />
	<ExamplesUiAlert6 />
	<ExamplesUiAlert7 />
	<ExamplesUiAlert8 />
	<ExamplesUiAlert9 />
	<ExamplesUiAlert10 />
	<ExamplesUiAlert11 />
	<ExamplesUiAvatar />
	<ExamplesUiAvatar2 />
	<ExamplesUiAvatar3 />
	<ExamplesUiAvatar4 />
	<ExamplesUiAvatar5 />
	<ExamplesUiAvatar6 />
	<ExamplesUiBadge />
	<ExamplesUiBadge2 />
	<ExamplesUiBadge3 />
	<ExamplesUiBadge4 />
	<ExamplesUiBadge5 />
	<ExamplesUiBadge6 />
	<ExamplesUiBadge7 />
	<ExamplesUiBadge8 />
	<ExamplesUiBreadcrumb />
	<ExamplesUiBreadcrumb2 />
	<ExamplesUiBreadcrumb3 />
	<ExamplesUiBreadcrumb4 />
	<ExamplesUiBreadcrumb5 />
	<ExamplesUiButton />
	<ExamplesUiButton2 />
	<ExamplesUiButton3 />
	<ExamplesUiButton4 />
	<ExamplesUiButton5 />
	<ExamplesUiButton6 />
	<ExamplesUiButton7 />
	<ExamplesUiButton8 />
	<ExamplesUiButton9 />
	<ExamplesUiButton10 />
	<ExamplesUiButton11 />
	<ExamplesUiButton12 />
	<ExamplesUiButton13 />
	<ExamplesUiButton14 />
	<ExamplesUiButton15 />
	<ExamplesUiButton16 />
	<ExamplesUiButton17 />
	<ExamplesUiButton18 />
	<ExamplesUiButton19 />
	<ExamplesUiButton20 />
	<ExamplesUiButton21 />
	<ExamplesUiCard />
	<ExamplesUiCarousel />
	<ExamplesUiCarousel2 />
	<ExamplesUiCarousel3 />
	<ExamplesUiCarousel4 />
	<ExamplesUiCarousel5 />
	<ExamplesUiCarousel6 />
	<ExamplesUiCarousel7 />
	<ExamplesUiCarousel8 />
	<ExamplesUiCarousel9 />
	<ExamplesUiCarousel10 />
	<ExamplesUiCarousel11 />
	<ExamplesUiCarousel12 />
	<ExamplesUiCarousel13 />
	<ExamplesUiCarousel14 />
	<ExamplesUiCheckbox />
	<ExamplesUiCheckbox2 />
	<ExamplesUiCheckbox3 />
	<ExamplesUiCheckbox4 />
	<ExamplesUiCheckbox5 />
	<ExamplesUiCheckbox6 />
	<ExamplesUiCheckbox7 />
	<ExamplesUiChip />
	<ExamplesUiChip2 />
	<ExamplesUiChip3 />
	<ExamplesUiChip4 />
	<ExamplesUiChip5 />
	<ExamplesUiChip6 />
	<ExamplesUiChip7 />
	<ExamplesUiChip8 />
	<ExamplesUiCommandPalette />
	<ExamplesUiCommandPalette2 />
	<ExamplesUiCommandPalette3 />
	<ExamplesUiCommandPalette4 />
	<ExamplesUiCommandPalette5 />
	<ExamplesUiCommandPalette6 />
	<ExamplesUiCommandPalette7 />
	<ExamplesUiCommandPalette8 />
	<ExamplesUiCommandPalette9 />
	<ExamplesUiCommandPalette10 />
	<ExamplesUiCommandPalette11 />
	<ExamplesUiCommandPalette12 />
	<ExamplesUiContainer />
	<ExamplesUiContextMenu />
	<ExamplesUiContextMenu2 />
	<ExamplesUiContextMenu3 />
	<ExamplesUiContextMenu4 />
	<ExamplesUiDatePicker />
	<ExamplesUiDatePicker2 />
	<ExamplesUiDatePicker3 />
	<ExamplesUiDatePicker4 />
	<ExamplesUiDivider />
	<ExamplesUiDivider2 />
	<ExamplesUiDivider3 />
	<ExamplesUiDivider4 />
	<ExamplesUiDivider5 />
	<ExamplesUiDivider6 />
	<ExamplesUiDivider7 />
	<ExamplesUiDivider8 />
	<ExamplesUiDropdown />
	<ExamplesUiDropdown2 />
	<ExamplesUiDropdown3 />
	<ExamplesUiDropdown4 />
	<ExamplesUiDropdown5 />
	<ExamplesUiDropdown6 />
	<ExamplesUiDropdown7 />
	<ExamplesUiFormGroup />
	<ExamplesUiFormGroup2 />
	<ExamplesUiFormGroup3 />
	<ExamplesUiFormGroup4 />
	<ExamplesUiFormGroup5 />
	<ExamplesUiFormGroup6 />
	<ExamplesUiFormGroup7 />
	<ExamplesUiFormGroup8 />
	<ExamplesUiFormGroup9 />
	<ExamplesUiFormGroup10 />
	<ExamplesUiFormGroup11 />
	<ExamplesUiFormGroup12 />
	<ExamplesUiFormGroup13 />
	<ExamplesUiFormGroup14 />
	<ExamplesUiForm />
	<ExamplesUiForm2 />
	<ExamplesUiForm3 />
	<ExamplesUiForm4 />
	<ExamplesUiForm5 />
	<ExamplesUiForm6 />
	<ExamplesUiForm7 />
	<ExamplesUiHorizontalNavigation />
	<ExamplesUiHorizontalNavigation2 />
	<ExamplesUiHorizontalNavigation3 />
	<ExamplesUiIcon />
	<ExamplesUiIcon2 />
	<ExamplesUiInputMenu />
	<ExamplesUiInputMenu2 />
	<ExamplesUiInputMenu3 />
	<ExamplesUiInputMenu4 />
	<ExamplesUiInputMenu5 />
	<ExamplesUiInputMenu6 />
	<ExamplesUiInputMenu7 />
	<ExamplesUiInputMenu8 />
	<ExamplesUiInputMenu9 />
	<ExamplesUiInputMenu10 />
	<ExamplesUiInputMenu11 />
	<ExamplesUiInputMenu12 />
	<ExamplesUiInputMenu13 />
	<ExamplesUiInputMenu14 />
	<ExamplesUiInputMenu15 />
	<ExamplesUiInput />
	<ExamplesUiInput2 />
	<ExamplesUiInput3 />
	<ExamplesUiInput4 />
	<ExamplesUiInput5 />
	<ExamplesUiInput6 />
	<ExamplesUiInput7 />
	<ExamplesUiInput8 />
	<ExamplesUiInput9 />
	<ExamplesUiInput10 />
	<ExamplesUiInput11 />
	<ExamplesUiInput12 />
	<ExamplesUiInput13 />
	<ExamplesUiInput14 />
	<ExamplesUiKbd />
	<ExamplesUiKbd2 />
	<ExamplesUiKbd3 />
	<ExamplesUiKbd4 />
	<ExamplesUiLink />
	<ExamplesUiMeter />
	<ExamplesUiMeter2 />
	<ExamplesUiMeter3 />
	<ExamplesUiMeter4 />
	<ExamplesUiMeter5 />
	<ExamplesUiMeter6 />
	<ExamplesUiMeter7 />
	<ExamplesUiMeter8 />
	<ExamplesUiMeter9 />
	<ExamplesUiMeter10 />
	<ExamplesUiMeter11 />
	<ExamplesUiModal />
	<ExamplesUiModal2 />
	<ExamplesUiModal3 />
	<ExamplesUiModal4 />
	<ExamplesUiModal5 />
	<ExamplesUiModal6 />
	<ExamplesUiModal7 />
	<ExamplesUiModal8 />
	<ExamplesUiModal9 />
	<ExamplesUiNotification />
	<ExamplesUiNotification3 />
	<ExamplesUiNotification4 />
	<ExamplesUiNotification5 />
	<ExamplesUiNotification6 />
	<ExamplesUiNotification7 />
	<ExamplesUiNotification8 />
	<ExamplesUiNotification9 />
	<ExamplesUiNotification10 />
	<ExamplesUiNotification11 />
	<ExamplesUiNotification12 />
	<ExamplesUiNotification13 />
	<ExamplesUiNotification14 />
	<ExamplesUiNotification15 />
	<ExamplesUiNotification16 />
	<ExamplesUiNotification17 />
	<ExamplesUiNotification18 />
	<ExamplesUiPagination />
	<ExamplesUiPagination2 />
	<ExamplesUiPagination3 />
	<ExamplesUiPagination4 />
	<ExamplesUiPagination5 />
	<ExamplesUiPagination6 />
	<ExamplesUiPagination7 />
	<ExamplesUiPagination8 />
	<ExamplesUiPagination9 />
	<ExamplesUiPopover />
	<ExamplesUiPopover2 />
	<ExamplesUiPopover3 />
	<ExamplesUiPopover4 />
	<ExamplesUiPopover5 />
	<ExamplesUiPopover6 />
	<ExamplesUiPopover7 />
	<ExamplesUiPopover8 />
	<ExamplesUiProgress />
	<ExamplesUiProgress2 />
	<ExamplesUiProgress3 />
	<ExamplesUiProgress4 />
	<ExamplesUiProgress5 />
	<ExamplesUiProgress6 />
	<ExamplesUiProgress7 />
	<ExamplesUiProgress8 />
	<ExamplesUiProgress9 />
	<ExamplesUiRadioGroup />
	<ExamplesUiRadioGroup2 />
	<ExamplesUiRadioGroup3 />
	<ExamplesUiRadioGroup4 />
	<ExamplesUiRadioGroup5 />
	<ExamplesUiRadioGroup6 />
	<ExamplesUiRadioGroup7 />
	<ExamplesUiRadioGroup8 />
	<ExamplesUiRadioGroup9 />
	<ExamplesUiRadioGroup10 />
	<ExamplesUiRadioGroup11 />
	<ExamplesUiRange />
	<ExamplesUiRange2 />
	<ExamplesUiRange3 />
	<ExamplesUiRange4 />
	<ExamplesUiRange5 />
	<ExamplesUiRange6 />
	<ExamplesUiSelectMenu />
	<ExamplesUiSelectMenu2 />
	<ExamplesUiSelectMenu3 />
	<ExamplesUiSelectMenu4 />
	<ExamplesUiSelectMenu5 />
	<ExamplesUiSelectMenu6 />
	<ExamplesUiSelectMenu7 />
	<ExamplesUiSelectMenu8 />
	<ExamplesUiSelectMenu9 />
	<ExamplesUiSelectMenu10 />
	<ExamplesUiSelectMenu11 />
	<ExamplesUiSelectMenu12 />
	<ExamplesUiSelectMenu13 />
	<ExamplesUiSelectMenu14 />
	<ExamplesUiSelectMenu15 />
	<ExamplesUiSelectMenu16 />
	<ExamplesUiSelectMenu17 />
	<ExamplesUiSelectMenu18 />
	<ExamplesUiSelectMenu19 />
	<ExamplesUiSelectMenu20 />
	<ExamplesUiSelect />
	<ExamplesUiSelect2 />
	<ExamplesUiSelect3 />
	<ExamplesUiSelect4 />
	<ExamplesUiSelect5 />
	<ExamplesUiSelect6 />
	<ExamplesUiSelect7 />
	<ExamplesUiSelect8 />
	<ExamplesUiSelect9 />
	<ExamplesUiSelect10 />
	<ExamplesUiSelect11 />
	<ExamplesUiSelect12 />
	<ExamplesUiSelect13 />
	<ExamplesUiSkeleton />
	<ExamplesUiSlideover />
	<ExamplesUiSlideover2 />
	<ExamplesUiSlideover3 />
	<ExamplesUiSlideover4 />
	<ExamplesUiSlideover5 />
	<ExamplesUiSlideover6 />
	<ExamplesUiSlideover7 />
	<ExamplesUiSlideover8 />
	<ExamplesUiTable />
	<ExamplesUiTable2 />
	<ExamplesUiTable3 />
	<ExamplesUiTable4 />
	<ExamplesUiTable5 />
	<ExamplesUiTable6 />
	<ExamplesUiTable7 />
	<ExamplesUiTable8 />
	<ExamplesUiTable9 />
	<ExamplesUiTable10 />
	<ExamplesUiTable11 />
	<ExamplesUiTable12 />
	<ExamplesUiTable13 />
	<ExamplesUiTable14 />
	<ExamplesUiTable15 />
	<ExamplesUiTable16 />
	<ExamplesUiTable17 />
	<ExamplesUiTable18 />
	<ExamplesUiTabs />
	<ExamplesUiTabs2 />
	<ExamplesUiTabs3 />
	<ExamplesUiTabs4 />
	<ExamplesUiTabs5 />
	<ExamplesUiTabs6 />
	<ExamplesUiTabs7 />
	<ExamplesUiTabs8 />
	<ExamplesUiTextarea />
	<ExamplesUiTextarea2 />
	<ExamplesUiTextarea3 />
	<ExamplesUiTextarea4 />
	<ExamplesUiTextarea5 />
	<ExamplesUiTextarea6 />
	<ExamplesUiTextarea7 />
	<ExamplesUiTextarea8 />
	<ExamplesUiTextarea9 />
	<ExamplesUiTextarea10 />
	<ExamplesUiTextarea11 />
	<ExamplesUiTextarea12 />
	<ExamplesUiToggle />
	<ExamplesUiToggle2 />
	<ExamplesUiToggle3 />
	<ExamplesUiToggle4 />
	<ExamplesUiToggle5 />
	<ExamplesUiToggle6 />
	<ExamplesUiTooltip />
	<ExamplesUiTooltip2 />
	<ExamplesUiTooltip3 />
	<ExamplesUiTooltip4 />
	<ExamplesUiTooltip5 />
	<ExamplesUiVerticalNavigation />
	<ExamplesUiVerticalNavigation2 />
	<ExamplesUiVerticalNavigation3 />
	<ExamplesUiVerticalNavigation4 />
	<ExamplesUiVerticalNavigation5 />
	<ExamplesUiVerticalNavigation6 />
</template>
